Update deploy_by_ssh.yml

diff --git a/.github/workflows/deploy_by_ssh.yml b/.github/workflows/deploy_by_ssh.yml
--- a/.github/workflows/deploy_by_ssh.yml
+++ b/.github/workflows/deploy_by_ssh.yml
@@ -25,15 +25,18 @@ jobs:
           key: ${{ secrets.DEPLOY_SSH_KEY }}
           port: ${{ env.SSH_PORT }}
           script: |
-            if [[ -d /home/${{ env.SSH_USERNAME }}/Crystall/ ]]; then
-              sudo chmod -R 777 /home/${{ env.SSH_USERNAME }}/Crystall/ && echo "chmod done"
-              sudo chown -R ${{ env.SSH_USERNAME }}:${{ env.SSH_USERNAME }} /home/${{ env.SSH_USERNAME }}/Crystall/ && echo "chown done"
-            else
-              echo "/home/${{ env.SSH_USERNAME }}/Crystall/ not found"
-            fi
-          #   [[ -f /home/${{ env.SSH_USERNAME }}/Crystall/ ]] \
-          #   && sudo chmod -R 777 /home/${{ env.SSH_USERNAME }}/Crystall/ \
-          #   || echo "/home/${{ env.SSH_USERNAME }}/Crystall/ not found"
+            # if [[ -d /home/${{ env.SSH_USERNAME }}/Crystall/ ]]; then
+            #   sudo chmod -R 777 /home/${{ env.SSH_USERNAME }}/Crystall/ && echo "chmod done"
+            #   sudo chown -R ${{ env.SSH_USERNAME }}:${{ env.SSH_USERNAME }} /home/${{ env.SSH_USERNAME }}/Crystall/ && echo "chown done"
+            # else
+            #   echo "/home/${{ env.SSH_USERNAME }}/Crystall/ not found"
+            # fi
+            [[ -f /home/${{ env.SSH_USERNAME }}/Crystall/ ]] \
+            && sudo chmod -R 777 /home/${{ env.SSH_USERNAME }}/Crystall/ \
+            || echo "/home/${{ env.SSH_USERNAME }}/Crystall/ not found"
+            [[ -f /home/${{ env.SSH_USERNAME }}/Crystall/ ]] \
+            && sudo chown -R ${{ env.SSH_USERNAME }}:${{ env.SSH_USERNAME }} /home/${{ env.SSH_USERNAME }}/Crystall/ \
+            || echo "/home/${{ env.SSH_USERNAME }}/Crystall/ not found"
             
       - name: Refresh content
         uses: webfactory/ssh-agent@v0.5.4
